// app/layout.tsx
import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/footer";
import { FeedbackProvider } from "@/components/feeback/feedback-context";
import FeedbackModal from "@/components/feeback/feedback-modal";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${poppins.variable}
          ${inter.variable}
          antialiased
          flex
          flex-col
          min-h-screen
          sm:min-h-[100dvh] 
          overflow-x-hidden
        `}
      >
        <FeedbackProvider>
          <main className="flex-1 w-full flex flex-col relative">
            <div className="w-full flex-1">{children}</div>
            <FeedbackModal />
          </main>
        </FeedbackProvider>

        <Footer />
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
