import type { Metadata, Viewport } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { FeedbackProvider } from "@/components/feeback/feedback-context";
import FeedbackModal from "@/components/feeback/feedback-modal";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: "#000000",
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{ backgroundColor: "#000000" }}>
      <body
        className={`
          ${poppins.variable}
          ${inter.variable}
          antialiased
          flex
          flex-col
          min-h-dvh 
          bg-black 
          text-white
          overflow-x-hidden
        `}
      >
        <FeedbackProvider>
          <main className="flex-1 w-full flex flex-col relative pb-[env(safe-area-inset-bottom)]">
            <div className="w-full flex-1">{children}</div>
            <FeedbackModal />
          </main>
        </FeedbackProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
